### ISSUE TITLE
Chart part Django 

### ISSUE THREAD

**Issue by Schaffora** [Schaffora/ReEduc#7]
Trouver, tester et apprendre à configurer un framework ou autre permettant la création de graphe.

**Comment by Schaffora** [comment]
J'ai trouvé l'app  Graphos, celle-ci permet la création d'un grand nombre de type de graphe différent, est simple à prendre en main et surtout adapté à Django. Plus d'information sur: http://agiliq.com/demo/graphos/tutorial/

**Comment by greut** [comment]
https://djangopackages.org/grids/g/charts/

Graphos ne serait pas Python3

**Comment by Schaffora** [comment]
" Graphos is compatible with Python 2.7 and Python 3.3"-> On trouve cette information à la section compatibility du lien ci-dessus.

**Comment by greut** [comment]
@Schaffora l'auteur a mal fait son `setup.py`, du coup. le site est perdu. https://pypi.python.org/pypi/django-graphos/0.3.41

Et, prudence: https://travis-ci.org/agiliq/django-graphos

**Comment by Schaffora** [comment]
Devrais-je donc dévier sur une autre App ?

**Comment by greut** [comment]
https://djangopackages.org/grids/g/charts/ la ligne _Development Status_ est un bon indicateur du risque que vous prenez en faisant tel ou tel choix. Par risque, j'entends devoir débogguer la bibliothèque.

**Comment by greut** [comment]
D'autre part, essayez de réutiliser ce que vous avez appris lors de l'application Laravel en partant avec un outil connu.

**Comment by Schaffora** [comment]
Merci beaucoup, je vais utiliser Chartit, qui est adapté à python 3. L'idée de réutiliser le projet Laravel est bien, mais je suis aussi là pour apprendre et tester les différentes possibilités qu'il existe :P

**Comment by greut** [comment]
Je ne pensais pas à ça. ChartIt utilise HighCharts alors que votre projet StayFit utilisait Lavacharts -> Google Charts. Hélas la bibliothèque qui utilise Google Charts semble abandonnée.

Voilà qui met un peu plus en confiance:

* https://travis-ci.org/chartit/django-chartit
* https://travis-ci.org/areski/django-nvd3

Bonne suite!

**Comment by Schaffora** [comment]
Merci ;) 

Je veillerai à vérifier sur travis-ci.org pour la compatibilité la prochaine fois !

**Comment by greut** [comment]
La documentation et les tests sont généralement de bons facteurs pour un go/nogo.
